version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: poli1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: poli1234
    ports:
      - "3307:3306"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: test
      MYSQL_USER: root
      MYSQL_PASSWORD: poli1234